#!/usr/bin/env python3
"""
Demonstration of the buy/sell inference implementation.

This script shows how the enhanced detect_buy_sell method works with example data.
"""

def demonstrate_buy_sell_inference():
    """Demonstrate the buy/sell inference with example scenarios"""
    
    print("\n" + "=" * 80)
    print("🎯 BUY/SELL INFERENCE DEMONSTRATION")
    print("=" * 80 + "\n")
    
    # Example 1: BUY scenario
    print("📊 Example 1: BUY Trade")
    print("-" * 80)
    print("Scenario: User swaps 0.5 WSOL for 1000 tokens")
    print()
    print("preTokenBalances:")
    print("  - WSOL: 1.0")
    print("  - Token: 0.0")
    print()
    print("postTokenBalances:")
    print("  - WSOL: 0.5 (decreased by 0.5)")
    print("  - Token: 1000.0 (increased by 1000)")
    print()
    print("Inference Logic:")
    print("  ✓ Token delta > 0 (increased)")
    print("  ✓ WSOL delta < 0 (decreased)")
    print("  → action = 'buy'")
    print("  → mint_in = WSOL (So111...)")
    print("  → mint_out = Token")
    print()
    print("Expected Log Output:")
    print("  🟢 [DELTA_DETECTION] BUY detected: WalletAd.../TokenMin... +1000.000000 (WSOL: -0.500000)")
    print("  🎯 Detected action=buy")
    print("     Mint In: So11111111111111111111111111111111111111112")
    print("     Mint Out: TokenMint111...")
    print()
    
    # Example 2: SELL scenario
    print("📊 Example 2: SELL Trade")
    print("-" * 80)
    print("Scenario: User swaps 500 tokens for 0.3 WSOL")
    print()
    print("preTokenBalances:")
    print("  - WSOL: 0.5")
    print("  - Token: 1000.0")
    print()
    print("postTokenBalances:")
    print("  - WSOL: 0.8 (increased by 0.3)")
    print("  - Token: 500.0 (decreased by 500)")
    print()
    print("Inference Logic:")
    print("  ✓ Token delta < 0 (decreased)")
    print("  ✓ WSOL delta > 0 (increased)")
    print("  → action = 'sell'")
    print("  → mint_in = Token")
    print("  → mint_out = WSOL (So111...)")
    print()
    print("Expected Log Output:")
    print("  🔴 [DELTA_DETECTION] SELL detected: WalletAd.../TokenMin... -500.000000 (WSOL: +0.300000)")
    print("  🎯 Detected action=sell")
    print("     Mint In: TokenMint111...")
    print("     Mint Out: So11111111111111111111111111111111111111112")
    print()
    
    # Example 3: Fallback scenario (no WSOL context)
    print("📊 Example 3: Fallback (No WSOL Context)")
    print("-" * 80)
    print("Scenario: Token balance increases, but no WSOL change visible")
    print()
    print("preTokenBalances:")
    print("  - Token: 0.0")
    print()
    print("postTokenBalances:")
    print("  - Token: 100.0 (increased by 100)")
    print()
    print("Inference Logic:")
    print("  ✓ Token delta > 0 (increased)")
    print("  ✗ No WSOL delta available")
    print("  → action = 'buy' (fallback)")
    print("  → mint_out = Token")
    print()
    print("Expected Log Output:")
    print("  🟢 [DELTA_DETECTION] BUY detected: WalletAd.../TokenMin... +100.000000")
    print("  🎯 Detected action=buy")
    print("     Mint Out: TokenMint111...")
    print()
    
    # Summary
    print("=" * 80)
    print("📋 SUMMARY")
    print("=" * 80)
    print()
    print("Key Features:")
    print("  ✅ WSOL balance tracking (not skipped)")
    print("  ✅ Smart buy/sell inference based on WSOL + token deltas")
    print("  ✅ mint_in and mint_out saved for executor routing")
    print("  ✅ Enhanced logging with 🎯 Detected action format")
    print("  ✅ Fallback logic for edge cases")
    print()
    print("Benefits for Executors:")
    print("  • Know exact input/output tokens (mint_in/mint_out)")
    print("  • Can construct correct swap paths")
    print("  • Better routing decisions")
    print("  • Reduced execution errors")
    print()
    print("=" * 80 + "\n")

def show_executor_usage():
    """Show how executors can use the enhanced action data"""
    
    print("=" * 80)
    print("💡 EXECUTOR USAGE EXAMPLE")
    print("=" * 80 + "\n")
    
    print("How executors can use the enhanced action data:\n")
    
    print("```python")
    print("# Get detected balance actions from trade_info")
    print("actions = trade_info.get('detected_balance_actions', [])")
    print()
    print("for action in actions:")
    print("    action_type = action['action']      # 'buy' or 'sell'")
    print("    mint_in = action.get('mint_in')     # Input token mint")
    print("    mint_out = action.get('mint_out')   # Output token mint")
    print("    amount = action['amount']            # Trade amount")
    print()
    print("    if action_type == 'buy':")
    print("        # BUY: WSOL → Token")
    print("        # Construct swap: from mint_in to mint_out")
    print("        execute_swap(")
    print("            input_mint=mint_in,      # WSOL")
    print("            output_mint=mint_out,    # Token")
    print("            amount_in=0.001          # Investment amount")
    print("        )")
    print()
    print("    elif action_type == 'sell':")
    print("        # SELL: Token → WSOL")
    print("        # Construct swap: from mint_in to mint_out")
    print("        execute_swap(")
    print("            input_mint=mint_in,      # Token")
    print("            output_mint=mint_out,    # WSOL")
    print("            amount_in=token_balance  # Sell amount")
    print("        )")
    print("```")
    print()
    print("=" * 80 + "\n")

if __name__ == "__main__":
    demonstrate_buy_sell_inference()
    show_executor_usage()
    print("✅ Demonstration complete!\n")
